apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  selector:
    matchLabels: { app: kube-vip }
  template:
    metadata:
      labels: { app: kube-vip }
    spec:
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kube-vip
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

      # ensure the pod can resolve your masters by name (belt + braces)
      hostAliases:
        - ip: "$(KUBEVIP_MASTER_01_IP)"
          hostnames: ["kmaster01"]
        - ip: "$(KUBEVIP_MASTER_02_IP)"
          hostnames: ["kmaster02"]
        - ip: "$(KUBEVIP_MASTER_03_IP)"
          hostnames: ["kmaster03"]

      containers:
        - name: kube-vip
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          image: ghcr.io/kube-vip/kube-vip:$(IMAGE_KUBEVIP_TAG)
          # run in control-plane ARP mode, all params as flags (no DNS/CM lookups)
          args:
            - manager
            - --arp
            - --controlplane
            - --leaderElection
            - --interface=$(KUBEVIP_INTERFACE)
            - --vip=$(KUBEVIP_VIRTUAL_IP)
            - --cidr=$(KUBEVIP_VIRTUAL_IP_CIDR)
          env:
            # hard-pin the in-cluster API address so no 'kubernetes' DNS is needed
            - name: KUBERNETES_SERVICE_HOST
              value: "$(KUBEVIP_KUBERNETES_SERVICE_IP)"
            - name: KUBERNETES_SERVICE_PORT
              value: "$(KUBEVIP_KUBERNETES_SERVICE_PORT)"
          securityContext:
            capabilities:
              add: ["NET_ADMIN","NET_RAW"]
