apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:121DEfhNPOjMm23XfsbfKpE/5DEbB81D2H/Fbg/BSONIUpXIcUqm9n9M4Xn5yrLIvv/bAvh5fi1xsuwxH3vz3LSDixNWIlunF3Lk2EN3aSFtpwTghjBH6OPJPAjqWepr5HukXby3F7vCBN0qSOplBo85PV8ahTPTBZefebh6phfOhJ2xoni/NvmQoyds041Q+oN0oc2X8QP0cWRplh/l5hgppmFfUiIL8rJaX9B/n4c19pVai3qQQw==,iv:am+mkCBQ0Zkm2Lg8QG9wln4OwT+f4EkVrvowqQX9Qa4=,tag:Ac2aJdXDwFBCxksJl33LyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxS2RHV0N5WUlEdkRpa0NX
            TzJsU3ZxVGN6R2VuU3IyTUFNM3EwNGQ0ZGhnCjBKVUUrZmhPY3gvYzd1S1NES3FP
            b00zaXd1eWh2cVluZFFIN1YxeVpYdncKLS0tIDl1VkcvdWJrYWlCc0RVV1ZicDBu
            b0VwMnVIeVFiTFJSejN2aTU0Z2NpWWsKTdGVTitMpIzEcNzWvz2vddgg4QmXaTqh
            e76CptcgqoPeuzNqH0WLmGRmOdHGJAfDvEphfeVznqL9BwyTgSoE7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T21:22:20Z"
    mac: ENC[AES256_GCM,data:Io+RS0JB/+RHls+CcXnNT4sjwTyubIywr3PnBzZqtkboTHwaNQ68cOmFZzLRIYgiryCMok7xl15TUSv4G8GRqSoLnU9DH3cwsjOj5F968ksGy3GMbukAlkQHUQzd9RF6L3NJnV2PfR3kiKS+R2gZPWlAoKhwe4PDclWlwLhUE54=,iv:sCsmlmZoxu/hS5aDMIWulbD6eohyDPjpZqPjFYxMgfo=,tag:bs4pxA8dZqhDwa3aIQ0QTQ==,type:str]
    version: 3.13.1
