apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets/deadman-secret.sops.yaml
  - helmrelease.yaml
  - dashboards/smartctl.yaml
  - dashboards/hardware.yaml
  - rules/hardware.yaml
  - rules/cluster.yaml
