apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 12h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 37.1.2
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 30m
  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: "192.168.0.169"
      externalTrafficPolicy: Local
    deployment:
      replicas: 2
    resources:
      requests:
        cpu: 10m
        memory: 200Mi
        ephemeral-storage: 50Mi
    tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 60
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 60
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname
    tlsStore:
      default:
        defaultCertificate:
          secretName: bijouxlabs-wildcard-tls
    additionalArguments:
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
      - "--serversTransport.insecureSkipVerify=true"
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
