apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-bouncer-key
    namespace: crowdsec
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:GujEvKfohDqpiq1dz4ECsPTj11l+9xhZ2Vp8HaInGxsi4pdQK9FpG+hBA+hHvZVxP7wE3xck+93jSpm/GXkZNg==,iv:o0kxEimGOU9WxuLnf4hPGgOLYHu04DFQ2x0k4fuvFYA=,tag:CMjPhHweCzDtHiQM7NpEew==,type:str]
sops:
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRThJeHZySThUR3lJUllK
            Yzl5a3NMWUNBeDcyWllpVzVZWnZkNTRCTEd3CjhvTE1MK1FMakROOFhVc0V4dkti
            d3lvVHQxdTRvNDNYazVTT2JmM25xSncKLS0tIGVUck41blNnTFlBY0FFMENWWjNW
            S1BtUHd1RUdaSWhXbklpakQ1cnhabmsKYA8sPZc+Y9LwdEyrK09l0vphfsuS7Ve1
            hcXdV6wze56iBDImGyBxYs3HRX9AYcnl5EVhRDhXeiyKTnimT0kkyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T06:46:48Z"
    mac: ENC[AES256_GCM,data:SigvW1NY2DuGegJLQxmia2ywIfhGMU7vTlJhfKdYr+Xpl7xkfiXI+aPkGWOsecdEOMhrRXNdsVdJBH16VjBek0zPNFycd+sJAzbMLzu+CsjBbexk2Jj+RYWsnPVfa4PUQqzM2UosRoDswTDaF4hMIZOy6LhhNoVLiuhRn0WXDtI=,iv:ivm7o7VJKe3qFVX8F7PUUCxrpTPCwuPpOUWc12XxmGg=,tag:EcA669G6MbojITrAm0Uf8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
