apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: stefhq
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:DVWORdXzwMfokQMbo09TkpFVpBQF+OgKnNZS3mOjhFZXlh1OQZ3rWiraRFqMQdPYliRckAOwT/ZX6ZmNfzpuXaHgyu9aV74WPFiMfy1iaSjnfDVMfkPJm6EcgHBvpdkb,iv:NYSj8nA4euHqrZMZSiUOGrtbyq03U5JKlSc8JedENuo=,tag:2vthp+ZX/6klE+8jnFxelA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeGk4eDVXdG5Jcis2MWYx
            Y2lObEdCTmEvY1RVM0h1bitlc01pK3ZncFg4Clh2Wk5tS2VDdk5MclJ2RWhIbDJi
            VG9WYkUyMEVBTWNzeElGK3dIeU1wdU0KLS0tIE9HbGZHMjdnZXNxY1ZQeTR1TU5h
            Mm9pWmg3eEN1aFVRcmM2VTlBeUpSaTQKA4xDUkq2i5nW8RiuOYkoovwbcoRVZ32v
            PC/RYFj/goXlG7WlYqCFviy3Ltmv2q6z1cq1kDtih7jDLv7mZZToRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T20:38:27Z"
    mac: ENC[AES256_GCM,data:aG+3WHO8If0CKvl30DXNXztQzXLcmc4Keh1pkgEe0Eg5O3i1RHuFGXAoiEtEqUKfz/stxi1nxz+0dImjsme3jVAmefI8E2nw1bpURE0F/Gx5Gdsp6eNTdDy16okMhN5unGlzUnA/fRF8K5hH5eZ/a3DrmUGnNsDP8P5QJqjKAkE=,iv:LcwP5uPFN0T/WAHcflRSGcEIxPzR9ais4JhY7e5iduw=,tag:tPLvJhof9m1yudtk1nxcJg==,type:str]
    version: 3.13.1
