apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:bkIOB4NXVNtGIOhkDRPLpcwMDp1Eb1U01wrtnldRdoF7NCLkavPKMAXdVdfvzgiiy9X0ssFbalkJN3wUxMPsaQ==,iv:3dQF1haxr5ok7JW2DryLCJyWS8U/9gxhwIH69j5cZNI=,tag:2vnBkYp+ruOceLi9O6C2AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR2VJdVVFOEQ3bWR1OTI1
            elc3dTkrYjdZdDFGQjl5TVJXOHY5b2t4V0E0CnZ4Q0M4d1FCTE1Ya1hWaXNidDQw
            TDdiV2FKc3B4RmsyME1mNmpHeEhIYjQKLS0tIHFOMGV4WWdGRXNSMGFnZHhTNmtH
            bmNheDZVbHFEUEFjbXpkVUlFMWtoMHMKgPmsJfxzIGnhzy+SuIw8wRFMnNh6TVsP
            CLLxwsrW8uU32f7XjTTXRvsPhOV0nhjbf3YLcf6KFrMM1Ozr4NchmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T13:00:06Z"
    mac: ENC[AES256_GCM,data:iNFHGmKbQ0V/jI+pN/i7vyRLcptFHW5z4uG6YwL6TuplHFgmTt6uP/tKC67m3wOm1AUdNn8IjJ/6/AacS1ZnUPZ5dQ2xLhSCZelbweJ1LSmI5heHdH6U6y2ia/m05IRw0WG7YUbVNzOQ4gUOc3JSzWzB4pPq30NjN3VYdIb/wpU=,iv:6uJYNHdiUyyJ4lWBfF1AWJR5eq1whtCNASsNmzncUnE=,tag:xDKQZIqt145W5Yqf100Lzw==,type:str]
    version: 3.13.1
