apiVersion: v1
kind: Service
metadata:
  name: tauc-speedtest
  namespace: $(NAMESPACE_APPLICATIONS)
  annotations:
    metallb.universe.tf/loadBalancerIPs: $(LB_IP_TAUC_SPEEDTEST)
spec:
  type: LoadBalancer
  selector:
    app: tauc-speedtest
  ports:
    - name: http-8089
      port: 8089
      targetPort: $(PORT_TAUC_SPEEDTEST)
      protocol: TCP
