apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:ZK0W9ANwjAAuwXzQJLwLmHI62vRw9Q3E52QQOG+IZdMEFbeh6FpVcRq3h55bb2LqouB7ZivyU7X8KcXcFqsm0w==,iv:1iOUZPBlZ/O/cE+2xY/BJrLZtZRczJAHOi6JR7veBLI=,tag:gKswAh+bnhQtXYB+iC6DWQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:U7I0s8c=,iv:SoPbD7ke2SoDQ0uL9tlERCfev2WnO2+LCxYCjFQgMbI=,tag:krHta6W63NrK86nOLUdEgg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:CA/7TMyw3i2WuoI1eYw=,iv:4EhQUWiISqgEjp43vbOi1LnszmACc+7XAU2mFSVZiZI=,tag:JZTPqF57Ol9CyWX38QQ/7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRzIxZEtNVU5aNWJQTWxs
            S0FlVmsxZVZQc0xqc1hTMXE2Z0o0QkxhejA4CnhyYlRnSHpJWHpPZUViTWZQaUNW
            aGdLL0JNV1VDaTBlOXNPRkFGKzRxalUKLS0tIGdza1FXU0RmZUwyQjZpeVpXaGhG
            Z3RyQm1tVnVwT0tRTm52ZWpVUHl0N0EK45b7sCggreydAursfS5zKurJ3eCvguzc
            RgWIo2MoJXRqRWGcvnumrRtJ9Ib43IrYnlFzRkpx6rNlMZyH+iz6rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T14:55:42Z"
    mac: ENC[AES256_GCM,data:Nzyn0Cazjhazul8bQqi0ubXSduy+VdZuif8BdvVrvun/dNRZZvXusuyLpXTtpP55aiy7q7HCziSiEwONS6TS7HKdr4Y6Cb6kTszSa0e2zrdgQyoToNDzqz2niuXBvDPVv8lOgC+t7VLKTml0oiJ4S773GFxsTlk5ziIlzjx6E4o=,iv:aifOP8NwcoMSUiqn8FcJxZ2Qm5cG7lLJBQOgsUNp2A4=,tag:badHpXEOeccrnvyMyfjsCw==,type:str]
    version: 3.13.1
