apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
    namespace: netbox
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:yW3EXjnDeBAooexIEmm/9OPEJzLpSQyNAn00PcQjtz0oVy1//RG/F4BMpIOg7/ccHV+FlWs/COHOxDss,iv:fKtDsTDAbXJyPv+kP4xUhllZ75mZ2MYxezmQhh2uCWI=,tag:ba0jnia5imyzjB0uuuenhg==,type:str]
    username: ENC[AES256_GCM,data:aQevqqY=,iv:aBkUqvnQJ6ohnXqqgN2FgCIdMGF3lp9ibSg9wMBitIQ=,tag:xe34RvpitPbbJOHsSV7koQ==,type:str]
    password: ENC[AES256_GCM,data:hLH5X1dwSUYjBEyCCy5mvgmgkyvLqHCZ3G6w,iv:LjkLW3ErvPbiD/Y0yxI8NOclsCjcrUMihRefAXxK+KE=,tag:dUvFqZVD0tK97UK0AM8qBQ==,type:str]
    email: ENC[AES256_GCM,data:RlM9l6GV0RB6ocI8B8YGHe98QMcheGw=,iv:KuW9CMAR0/iXC82jpPnbfOmwwSdbZ1s/TX0S3XzsWHc=,tag:UFh0SdOxLJetoW1fGFOXQg==,type:str]
    api_token: ENC[AES256_GCM,data:XYjJJslVDZ+LMS/OWtwWcRC526ma1kqhPC4RuPcoLo7STrzf,iv:RIgNij6BvgWhs0zShMGvNQlPKnRguDVORVTNFmfUt8c=,tag:r052IUKzwCTBIsmAb/eQdg==,type:str]
    postgresql-password: ENC[AES256_GCM,data:88FU4L1arZxmWvMdlbeGEJpCHpsK7Z3g/q7y,iv:EACjiNdEZvbFUhSjPGRZNxvIRtAM3LW9KlfaQYOxeQ8=,tag:WJqwQuo7sH5y6KqBsqgeqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOXI0bWd6aWhFTFhVREZi
            clJKNy96VjFxNVFUMzVmSjE1L0lXcTNSRFNBCnA4ZGRicjNOQWZrVU90MTFiQXlw
            NWkyRHVDTndMMVo3Um5lc1g4NzQyWUEKLS0tIGxRYnVRUHlHK0JleWgvZzhYYWJs
            emZJemJVU3pDMlRvTEs5OEJISGFmOVEKMPznljj1EJa4Vp9WhySRdG/zPZa7NsMM
            vgtDh38RVU1VLvrurmfMWWBRFqw5A54GvL62suidr1otanzKXJKLuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T18:00:52Z"
    mac: ENC[AES256_GCM,data:+HZUL6rfUGhQbnIZAfEtrjjk8Q7VllaU59MWVl89MDKK6JobuW1aft7C5wSExBexN7Q/uJI3C0ZMNKSGe4mWfcbTbxjUXshtbOQxpdhWL53bMhjnZNll89p69tfT0z8LhstwHDd7XF7BXTDgZx/YhaxEt4v14YkY/lty86LvCtQ=,iv:zyNDEOm+BedG9fxP1g8NBn8cDT9LHoXc7CIxViescR0=,tag:cA7iNdhDYBv4dlJSX1mACQ==,type:str]
    version: 3.13.1
