apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - library-pvc.yaml
  - secrets/db-secret.sops.yaml
  - database-cluster.yaml
  - helmrelease.yaml
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: immich
      app.kubernetes.io/part-of: immich
