# Flux CD - Public Environment Variables (Defaults/Placeholders)
# This file contains default placeholder values for public deployment
# Replace with actual values in private overlay or environment-specific overlays

# =============================================================================
# NETWORK CONFIGURATION
# =============================================================================

metallb:
  ipPoolStart: "192.168.1.100"
  ipPoolEnd: "192.168.1.110"
  subnetCIDR: "192.168.1.0/24"
  allowedSubnets:
    - "192.168.1.0/24"
    - "10.0.0.0/8"

kubeVIP:
  virtualIP: "192.168.1.1"
  virtualIPCIDR: "32"
  interface: "eth0"
  controlPlaneIPs:
    kmaster01: "192.168.1.10"
    kmaster02: "192.168.1.11"
    kmaster03: "192.168.1.12"
  kubernetesServiceIP: "10.43.0.1"
  kubernetesServicePort: "443"

loadBalancerIPs:
  traefik: "192.168.1.100"
  longhorn: "192.168.1.101"
  opengist: "192.168.1.102"
  taucSpeedtest: "192.168.1.103"
  iperf3: "192.168.1.104"

externalServices:
  homeAssistant:
    ip: "192.168.1.50"
    port: "8123"

# =============================================================================
# DOMAIN & DNS CONFIGURATION
# =============================================================================

domains:
  base: "example.com"
  services:
    opengist: "opengist.example.com"
    homeAssistant: "homeassistant.example.com"
    netdata: "netdata.example.com"

tls:
  certResolver: "letsencrypt"
  ingressClass: "traefik"
  redirectHttpToHttps: "true"

# =============================================================================
# KUBERNETES NAMESPACES
# =============================================================================

namespaces:
  traefik: "traefik"
  longhorn: "longhorn-system"
  kubeVip: "kube-system"
  metalLb: "metallb-system"
  applications: "default"

# =============================================================================
# CONTAINER IMAGES & REGISTRIES
# =============================================================================

images:
  kubeVip:
    registry: "ghcr.io"
    repository: "kube-vip/kube-vip"
    tag: "v0.8.0"

  opengist:
    registry: "ghcr.io"
    repository: "thomiceli/opengist"
    tag: "latest"

  netdata:
    registry: "docker.io"
    repository: "netdata/netdata"
    tag: "stable"

  iperf3:
    registry: "docker.io"
    repository: "networkstatic/iperf3"
    tag: "latest"

  nginx:
    registry: "docker.io"
    repository: "library/nginx"
    tag: "1.27-alpine"

  alpine:
    registry: "docker.io"
    repository: "library/alpine"
    tag: "3.20"

# =============================================================================
# HELM CHART VERSIONS & REPOSITORIES
# =============================================================================

helmCharts:
  traefik:
    version: "37.1.2"
    repository: "https://traefik.github.io/charts"

  longhorn:
    version: "1.10.0"
    repository: "https://charts.longhorn.io"

# =============================================================================
# APPLICATION PORT CONFIGURATION
# =============================================================================

ports:
  traefik:
    http: "80"
    https: "443"
  opengist: "6157"
  homeAssistant: "8123"
  netdata: "19999"
  iperf3: "5201"
  taucSpeedtest: "80"

# =============================================================================
# STORAGE CONFIGURATION
# =============================================================================

storage:
  traefik:
    persistence:
      path: "/data"
      size: "1Gi"
      accessMode: "ReadWriteOnce"
      storageClass: "standard"

# =============================================================================
# LONGHORN STORAGE SYSTEM SETTINGS
# =============================================================================

longhorn:
  replicaCount: "1"
  dataLocality: "best-effort"
  disableRevisionCounter: "true"
  orphanAutoDeletion: "true"
  defaultDataLocality: "best-effort"
  backupstorePollInterval: "300"

# =============================================================================
# SECURITY & RBAC CONFIGURATION
# =============================================================================

securityContext:
  speedtest:
    fsGroup: "101"
  opengist:
    fsGroup: "1000"

# =============================================================================
# NODE SELECTORS & TOLERATIONS
# =============================================================================

nodeSelectors:
  controlPlane:
    key: "node-role.kubernetes.io/control-plane"
    value: "true"

tolerations:
  controlPlane:
    key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: "300"
  master:
    key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

# =============================================================================
# TRAEFIK INGRESS CONTROLLER SETTINGS
# =============================================================================

traefik:
  logLevel: "INFO"
  dashboard:
    enabled: "true"
  metrics:
    prometheus:
      enabled: "false"
    datadog:
      enabled: "false"
  ingressClass: "traefik"
  service:
    loadBalancerIP: "192.168.1.100"
    type: "LoadBalancer"

# =============================================================================
# NETWORKING POLICIES
# =============================================================================

networkPolicies:
  allowHA_LAN: "192.168.1.0/24"
  allowAlternate: "10.0.0.0/8"
  denyIngress: "false"
  denyEgress: "false"

# =============================================================================
# REPLICA & SCALE SETTINGS
# =============================================================================

replicas:
  longhorn:
    manager: "1"
    engine: "1"
  opengist: "1"
  netdata: "1"
  speedtest: "1"

# =============================================================================
# RESOURCE REQUESTS & LIMITS
# =============================================================================

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# =============================================================================
# FLUX CONFIGURATION
# =============================================================================

flux:
  namespace: "flux-system"
  syncInterval: "5m"
  retryInterval: "1m"
  sourceRefreshInterval: "10m"
