apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty-data
  namespace: copyparty
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single
  resources:
    requests:
      storage: 50Gi
