apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: immich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9VOtDg72,iv:sXNIRjMEeJReTUnlWlP1/CgaZjnCfzJbhOlaqSeHM1c=,tag:/ZywmGTxMbtn3LGMcfio7w==,type:str]
    password: ENC[AES256_GCM,data:Itrhz7qOUa8JfFU=,iv:QLJlVk7KuqT/qWcjxzBNL6dcCfx6qyIJZJFi9C8TITs=,tag:OBn8uiPVfv4eKu93yorKgA==,type:str]
sops:
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dGRHUy9nUXpaQzE5UGh5
            WWN5MDdiVHFBN2twMnhoZm1kMjJJaEQxNHo0CjJSQXhnUUtURWRnUG5oK3ZPbmk1
            S2RlQUhKRGtwRFpoZ0RkL2hVcG5NQkkKLS0tIHhGVllsOXFGNjJRRktyUndQQmJv
            dFd5aEIydll1SGxWUDl1Q1U1NHZSKzgK5kOzUT5z9PfD0StdNyDHimmLaODmF/DW
            9ayMnKUCXD0Q44jU0pWZAkul07orXj5IvcKKrEbzUONgmJlXl/aUVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T07:19:30Z"
    mac: ENC[AES256_GCM,data:tS9A/2LxQHRv1LdOQ8hvOZskIptmqXbGC//GOsa3ok+JuHtKNOlouUKkrnz5c6srrYPsx1gwJZdpOCI76RjTq9vFke5NA6shF2eCeGq+hxoZNCkVJ7GcW3wqUsrH2TCESxruRMBJ1raxTbw7yuhWj4wQi4c9Jfiij8kgdAfjyTA=,iv:WYubWpMJajQBU9FVQ4Qy4BZ7bG0+gY4wwNJEqZDspXU=,tag:tyiruD0c4sImcyS2pvxilw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
