apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:EZVOn0+gMoleA/1TQ4UbCcuseY03n1DKjc2rsqzNEi6YTp5Vjmn07Q==,iv:Pp4oo5eMFCtrJ5k4A6wF92SCT41/8el9hHtg6bDDAm4=,tag:5JcSA5PbWe05f13eu7gFLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OEdlNmJ4QlI2eXo2Qngr
            ajNqSHZWZHQ1d1JHb05WVjdHUUZEbFNtOEdBCmI0QWk2SnpIQXUyM2wrcjFtUG1Q
            VHF1TTVzaHpYNmFVbjRNc1ZrMXF5b28KLS0tIG9GbEcwU2RiZTVvTTJKNHNadXd4
            VFlJbEtrV0x3dVpQVGZEbkprMU9BNDQKRCPfyG/QaKkph+dl0uYMT8l0N1ZtsIx/
            HV6h+7OIVq425CpSAYFgU7HTgF0W2duGkewisy3uqfSZfvGOst7zwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T13:45:36Z"
    mac: ENC[AES256_GCM,data:g4YbplS8Ofq7xVDXx+/RZVoO6U7Fj6tdalRunIa8q5Gjww2myvHGH+83BLrtoE/Xw3U/hfqdb0a0FtqrJQY+6RPOgwlMXwJXujxTquISNy2eoKEWKWRlwqEfJ/3ojprgPJpZzHBGwJ80QxtGqEfvjbTmk3+sVzN+PRKiz7/RRno=,iv:7FnLuiejfqdCRIuu+FLNbQAfcs7Axlszum2CO7j2EAI=,tag:MRGha5v874qArb08z5yJdA==,type:str]
    version: 3.13.1
