apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-deadman
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:paLMJ1wIboZd9MdZoNfbxz8epgKQg8LdnbtaUVFAvJWNl3yGJzZU/QdCIyidhiAmW7Qv8sfsr6CwJgx76PyebV+AnaagiL0YC6+Sww==,iv:SK3DfZPfuSvSlCHDMlY/Y8WMUsA5a1h++3X+ep4yhSM=,tag:ay0lCln8UMOzvEJdHesx0A==,type:comment]
    #ENC[AES256_GCM,data:hi3MxW8bMKvCZY5jiPzGScbJqZf0JTa+TQ0XQa6QwKtBUWqsV80cqGA2Zi86V16NSYGa++CpL3Js4dfUVSBcmFB+svEVbMBi2/65,iv:aTgbTuFmjTU4hl50lhrbOIZRGJJfJiiXdcwEsIAZjYA=,tag:XRBogfOqoruGwonGnQDykQ==,type:comment]
    #ENC[AES256_GCM,data:nQZC4aT+38t/8OKTz2FqohrQKwLn7ao1W+hwg6MUQCQCcdjPRtVV7avc1AJsPwD+iLVrTrk1NV6J8EoBpi0h5x5ccuR5jMHTL+s=,iv:zO4uS8GaI2azgXNyFLfqCOylojbR7KMojMUM8aDYj/A=,tag:+c2ODeYl+1MkgBiR5u8C9g==,type:comment]
    #ENC[AES256_GCM,data:vE/ZY/B0iw6YT6H9mVLpI598iYWXjvThdTaoziUn/I/BhCvciw==,iv:MlGTGaaY0qgReDBe/1a0TOEpYmUymdwtnswL9M54UdM=,tag:fAsYARLW0/F1HxX4r8NMiw==,type:comment]
    #
    #ENC[AES256_GCM,data:imZ5ucxu0MIu/PyWfVzrdD+eCE2Vyc3eCjqE8YyZ5971yG37G7G80HZG3mZsMLJqPnkE9ZiykwgTy37XkQ5j4V4ljXN5fo1ToyTYS04iEBaJEd4=,iv:QB4n6WuvxsCThyS4TyU6VXFG+grJ5LxYBau3zkNN5lI=,tag:+HJT/xv8zT/Fv4Jqve/XZg==,type:comment]
    #ENC[AES256_GCM,data:Lg2RTwmLpVUYB2ziKXXntw/EBb2FZjjhShaudFkZuAN4WBY1k1i9D2ur/Rpi2lbmC3GY23Vzlo0z3TpLHwUXtMYX5r87YHvN7TPs,iv:2Rqv+kS2UWRPOjS/VFF6HmDGPgRKRrixkOVmA9T/Wj8=,tag:aeLNBR04Vc64Ze6OTlGgTw==,type:comment]
    #ENC[AES256_GCM,data:XrxbgQOHiY+oTFT3MEJuFH4i,iv:AeOmpjWgaohgfsHpl0cSoEnGK3ty3b8Gdc11gOWpH2M=,tag:a0YZjjS9yG+3TStwLw0L1A==,type:comment]
    #
    #ENC[AES256_GCM,data:Rc4/01eQFmghX2YJ0jl/kcDLHjHIWShEVi+Np0+Ej/N7J9N0yLWi+ZWdbu61J8246TFKzHCRMC/EB39aj7ui1pLozJHOABKg9Tpicr11kr5PEHUqwA==,iv:d++PUErBUFDiIkbD/xp9Btka93zyM++NFRtz7fy4+Q8=,tag:cJUKF6KwuIBoU8MLXZnO0w==,type:comment]
    url: ENC[AES256_GCM,data:lf2swt32d70mjCJkqTYgYQitvxyrdGIFouTuteOO6KCOyNQAAVSxeE16G4jsDhwqiCnPlbY5Z84=,iv:BTELGTph6BxKmacdiHE39Ze6RgQAsOVXPpOhj/vstkg=,tag:tW3hyOu0dXif+zYoj1gaZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdmxSV3JvT0ZpNUkxd0pH
            azVOZlF2bzdUbDN3SWdZMVJmTFNBb1BCb0RRCmFJT3RYSlk4cEMzcTB3SlNIZitr
            MGIwRVpLajA2dVZsd3prYUJqNmNsSEkKLS0tIDVOSUlWN0pUZ2ZCcGFkWGVQTnRB
            d0VFdFFVbkxzdG9wczFYaktrME00WEUKFAchdrhP4X1ey6wBAlSe3UgCRD0piCUX
            dmlfMiM5lZ5kfEIeraOp4AXahcj17LppBtHkmKZnDQir/gUFD4kz5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T18:24:05Z"
    mac: ENC[AES256_GCM,data:BkZRdAC/A2RCm4V+J6OFE8MXLcD9XZEt/PCT16V7Q/Jyhjfo6qgq7E95rxAHi4g9d9778TPaP7bxrzLy6fuPo59Vgv6Hwjt0ivIFXe9r5ywQSC/pxW/JcFPJSFTKDxN5BFoHs51RH635E5fQyNSudnaxJ7f7XCOj3zsDYgsSJE8=,iv:DqJv+U9E77cwse9huFH7yDVePx9Ya6MVm+dtWhh5x+Q=,tag:83+SFzGlcVQk6mQl4/Y0Dw==,type:str]
    version: 3.13.3
