apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:NlsNlUqoks6EyfA2nmFZ/g1TdWyOUvuvxOEdTOA2v+ZIUUOBYbW1yfw9508mSJZNOOQZvGjp1zR8WlyU+vZVXw==,iv:G4+b/JkorJkPH5m5mh7sOEiFxIjbuBNaKda7O3vORhA=,tag:GF3ruMc1S7MDaM+mkBY/Lw==,type:str]
sops:
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eDN4TjV1MmtBRnQ5Y2pm
            NWZtQUtadG1mclZwemtVYm5ka0c4UFZ1OEY0CkFzT200UlI0WTE1SncxUEJabEN5
            NExZUmRrdnlnUkNQVDRCQXJKRzRwR28KLS0tIFZmRWpIcTVnSFd3NUZuOXcvOTRK
            NFJvMCtWQnJ4QUFGQmFwZitVTndwT3cKkzZsVbAS3TdWoa+mGG5gatRORHos934U
            P7hQuEeIod2ST8Baqt36EOt2racUnUn8JZLKnlftpjUrmQVLF2AuEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T19:10:23Z"
    mac: ENC[AES256_GCM,data:ZCInB1PdWvbGRDdcKGpX3PU+wGq24RCCgJg28D/sLv2o5zrZ9VxRyumo/5Lp0N8OnFLiW8AgZ0RJWS+7IGrKXEIzVBe/piIQ8OHq1Skbe2VPu5lwbAB06rQXHI/szrXxq07O6ioJODk8FFIkXiGzOZZOqupxYUQC/LhnnPe7oNI=,iv:EdaJO773dwnl4dLHxjAQljlkRE+5z9rqa8bm8K/jkb8=,tag:FfqkLx5Kd3si1VWrYu3q/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
