apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"          # reduce write amplification (use 3 for critical volumes)
  dataLocality: "best-effort"     # keep one replica near the pod when possible
  disableRevisionCounter: "true"  # reduces per-write overhead; better perf/wear
  fsType: "ext4"
