apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: netbox
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/netbox-community/netbox-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  releaseName: netbox
  chart:
    spec:
      chart: netbox
      version: "8.x"
      sourceRef:
        kind: HelmRepository
        name: netbox
        namespace: flux-system
  interval: 30m
  timeout: 15m
  values:
    existingSecret: netbox-secret
    superuser:
      name: admin
      email: angelo.bijoux@gmail.com
      existingSecret: netbox-secret

    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
      hosts:
        - host: netbox.bijouxlabs.cc
          paths:
            - /
      tls:
        - hosts:
            - netbox.bijouxlabs.cc

    persistence:
      enabled: true
      storageClass: longhorn-single
      accessMode: ReadWriteMany
      size: 5Gi

    postgresql:
      enabled: true
      auth:
        username: netbox
        database: netbox
        existingSecretName: netbox-secret
        existingSecretKey: postgresql-password

    redis:
      enabled: true
