apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-data
  namespace: ocis
  annotations:
    volume.longhorn.io/number-of-replicas: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
