apiVersion: v1
kind: Secret
metadata:
    name: primecrunch-credentials
    namespace: primecrunch
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:mOGxAbSxSOE3forWTA+vvAc3AxTLIaA=,iv:CbMkLSrdfRXoNpmfIS2Vzyi31Swh3xNzoq7kRVO13aQ=,tag:EAlCE5dG9Q4IHqftPBCjsg==,type:str]
    password: ENC[AES256_GCM,data:1SzqZRXYlNaeB0ip3ZA=,iv:vGJ1jqSvPmLzId0SyfObDGNF54s+O79R4yfllU7xMD8=,tag:zrFAiBRamO7NYlZIiywhjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRmdIZWdkcnhUOElDSUlQ
            NWhORjBYZURtdGVWb1E2Sm5ZZit0ejlDQlJBCmZzNmNZYjR0VWI5aTFiQ2JFbEI4
            TWVOc01PRWVRNmRMUmowNVhHUGMxeWMKLS0tIDQ2SkIyTnd6WjVRQ2dtMU0xUVdM
            VExLaDRkRWdjOTlLTUJ5QnpxVWZ3bTQKfZN3hc2rcwmKrvaAZ1kWcjgiW/tHqune
            srJZna1Fg/UGDxsc2YtG/QXqQ80CZEbg7F51I1SWQGMXsJafdhxqAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T09:59:37Z"
    mac: ENC[AES256_GCM,data:Pf2DEDX7RYsRUQNoS6PPagUV4u6Kg20ZnvIboI9ulsdyBWAudxdruUoOPEKRQHQHAJfCaJ9sEMY1D0CfgC0ODBnQgGra9qe67p37gsTjXAJLMVBHvJ22KjH5S6pHtrC2D6yBCZDspA5fF6ZMj7bz0jwB4f5ZRENe5mwBpOvrI0k=,iv:eOm/yy2NVKNGi3SJ3bclD4+LMX+uBI8mp+93A7G0HzY=,tag:+d9hOT04v828dqGqyiY8dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
