apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-data
  namespace: bijouxlabs
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
