apiVersion: v1
kind: Secret
metadata:
    name: longhorn-b2-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aaPYR3nLihCrTgxc4afEZTxj/1bCGFdf7A==,iv:d+H7mDhn/oby7VQaId3Bphi0Ij84Rom/qI0zS9Y3njs=,tag:lMQ6j2KRy43DvMjRqyqzqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:enW/I/O4abjyPS3kY4v4Ug9P3ESSrzFq5jYFD6BzwA==,iv:u9YhAyLOAD1NZNqpgmIYbFpVuMlXvNBQhQJSziUgi/s=,tag:Q0nX7vevmjTSdghsESikJA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:hBz9zFMiiBpYpbvZXufQIuQJdCW8dYLC4cIyEEvi/TbNmIRWzSXaYhc=,iv:1wOCWUvZ3DgeUJFEMG0S7VPBOW2bR7zkFEnf+BR+Dvw=,tag:vvib7qNKDiIhcXkE8d7iUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMFNjMUdwOVRpZ3I5dkJL
            STYrbUVXbnJmSEliUW9ramZTZlpBMEpIL0ZvCjJ1U1VMOW9NMG1JU0JhYTh5Um94
            U3BuWXRrZ0VwOVErQXlhZE5URTlsbkUKLS0tIHk1d2Z4a0NXSjFOSzJJT1VPS2VY
            SHF1MU5wV1F5bTQwR0JOQVdBek9jWmMKsx5IadtHkBlmAlnrhUchIc38+lQ5rjcq
            OOFLDC3RUVXi9orNlQKBdLTbsBSieFahSl9gJDlqVDcKZI08gjtc9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T14:30:44Z"
    mac: ENC[AES256_GCM,data:NOdfhCyamTSxea8h3xztGqj33lz1E5Czx5zf2c27eQF7xapXTIcaG3KipgBcpbF8rxwNty3DN+QHcIRRLxjtX5Rp8HcNwWqQESGaUJEjRTT88qId5mezDf+KaPzHFtSLslB2M6zVdUfG9sIV2p3aPJDAnBGHAR5Yqq7r6IK5mLc=,iv:I8VoStSOQFDqt2QQ6xPTFw5uHj9L427tnTV1uVDv9u8=,tag:pY9LP6PTz1XZ4iFa934uRA==,type:str]
    version: 3.13.1
