apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secret
    namespace: karakeep
type: Opaque
stringData:
    meilisearch_master_key: ENC[AES256_GCM,data:PRdZJafgV1qu4+IdbkWp5JaqV4LvfGnjomGQoXi8TJLScnKlieHPScK5k3xI7qXFBWeZvcCWApWxw7+C2tRfkg==,iv:2dRn39zHKTDasNC6n1Y3+1aCiJlXxJZORDe9tpVoBkA=,tag:149R6zc0KIXkknMuxI/PqQ==,type:str]
    encryption_key: ENC[AES256_GCM,data:7DnRlaYPQSYsGBPHaOybJielVjNzn2byIi0t6eBeH7N+qy48iRVf5Vn89oAHntonYeTKdGdXkFjKTdofIyAJYQ==,iv:RKMtxjJO85Rs5IKMI6942jXOLj1QRxoC3ZUprWlesvs=,tag:GnePWwhTYgJ42hWfNGm+Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMHIrdlNISEt5K3Q0dWdL
            MUE0S0MxZnM5WkJWMnduL1oyb21RV1JNTVdrCkE2MFVGOW1hbU0yN0h3bkZydzVx
            Z0pzQVZ0K2VkQVJMYmJJYThnSVEwKzQKLS0tIEhWdU5odmhMRGhEUzF3N1ZuQzN4
            ZDY5dG1sSytvTUc2enlBUnlDWllGYzQKrTqzbb/PW2bEzl+ygIOMtIfumTlfUlEx
            nhwCuwkdd1MosZdybczAlktKXSEat+5rSlgNjKy6O0cj3CAn2MN7Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T22:28:21Z"
    mac: ENC[AES256_GCM,data:/y/Nv1o6RNyRfOFsgnWb6JS6s44gy7UqrUjJ93TImvEQM0VtWAmFfSjtotqEWHcUuEDi+FPAZdDO+rU431PjO9OvA9U2mzz58VFIv85u2jiR6j4vmA52QZPu+Lxxb5VSLnESVrWjyvp4bTTIiz57kGDwVFeTp9wnMe88P4VByxY=,iv:XDOHbfOB/Njf81hNJegxvLbBPdrfiwNt/yEpdV+TVGs=,tag:b8z59RleVlXrJh+ZiQKfuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
