apiVersion: v1
kind: Secret
metadata:
    name: qdrant-secret
    namespace: qdrant
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:+4Lrx4iJb3leA9g/Q96ygDFqm1oZEghDW20ezARYS9ciPr0Hp9qiOcTmMmifk2RmeQoXpbWNiYkh/0tdlWMOOw==,iv:BJUxJ3O4xJLbuEkrXueCfvBFYcq1iv38iHGd386x95k=,tag:D6Lxaw/XgSd6JntBfio/Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbHdTdStpL2MySWxJbkw2
            Y0V1MEk4RUxjZlp6VjRYNkpKc1RVY25abGo4CldFckRFc2pQaXRibTlIUm5oTHVq
            L1g2VDRobWRGd1dMMzJUelNiRDA0R2cKLS0tIEtUSVc0Tm95UDdXbWhKVi9PZmR4
            NDR3aElycExYbVBMZlQ4VXl3RVR5OFkKd9kpadkpFqZuSc20LI/MGX8QVhhfgxDn
            pgSkEU3f1o7mjwUu1k2uMiC1qWAa/Ao3WzQVBA2YUQ2cj+F+Byxx+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T09:02:40Z"
    mac: ENC[AES256_GCM,data:fTfiuWiOqqP7+3t2I5XcDtLnDidtir+xbJEMAyKpSpSNJ05RgdUCOFbwi7WD29zGj9MqMg+XWXNUz7tlrL9w8qtKpcyBSk3KQA1Ar7F8z8rZDIDwhfGIEE6fcwrOmmhstbkiPPGE5A6om2WxfVm7QJ/kyLmv2nwiANIlbGTXi/k=,iv:PrcBrGQVgduhV5tIZ1iEbFltz6nUsSierV7eerqc6RY=,tag:MUfe6ttnQQxeNFINErc+Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
