apiVersion: v1
kind: Secret
metadata:
    name: ocis-admin
    namespace: ocis
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:Mx2DLnZ/eVXrsw==,iv:hAdD8bbz/G6VZ/3BLLx9NYctM7YxlhFnJDnCivGqEDM=,tag:XphJBBwEHUS/8xy19aPUNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SUt4STJhanFyd2dtMWVV
            S2IrNFY4MVEyaU1ldUFpRmRFMVQ5SGhxSWtnCnY3dUdPRmVINEh2RXd1Sm8wb21m
            Z0hPU2FjaHVITmN2YWdnK3hEa3A4VWMKLS0tIFlvMzZndDRhd0t1NTd5RkRGcGxl
            K1JFRTdpT1EvM3NoYXNHZzdEV2JEZDgK+frPP4M758IVOjBbaNfbLMmq3zWBLe3L
            yr9MHU/5htTZSSHIcH0oZJjqlyLXzmGPi/BjYH6Rt0GaC+KEJo3AAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T17:14:15Z"
    mac: ENC[AES256_GCM,data:M6PJCMmlfTKgCQ/iExv2t7Szz1nj/yZ3cUe50VbYanM+BnM4XeArjrDZ2xSGYibqUWX7Qzk4Y6EKQYnSFKgXkgcZXI7xCfhzOBxm7ryJz5HfQTmp+n/2/7ZcxaTOMth1W28AOcqnLHFVn9caxWYAmHjcfvC+p7+ylq5pw2lBax8=,iv:YO6lFOMTqg0oguY8wFWiTE9k2G47l5FYpRjsRwGOM6c=,tag:nrWa+QA25sBJhTXuhlZUwQ==,type:str]
    version: 3.13.2
