apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - copyparty
  - homeassistant
  - homepage
  - monitoring
  - immich
  - n8n
  - opengist
  - uptime-kuma
  - vaultwarden
  - radar
  - paperless
  - qdrant
  - ollama
  - primecrunch
  - karakeep
  - stefhq
