apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stefhq
  namespace: stefhq
spec:
  suspend: true
  interval: 10m
  chart:
    spec:
      chart: apps/stefhq/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  targetNamespace: stefhq
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
