apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:hrFUSOBAkGDEzTJgPnSwbzIOS4nBKCpJwH8SAzd0zZiSXcC1kvykDQJHaD3aoHWZZF10vSJP5sKYNRlrgBR0Pw==,iv:67iYD3CmH15lNBZEgyvpDZCP2OnzxPBbMFXIYKjaCII=,tag:ygKpOTBiisnvjqIEfDcENA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k8za0kdd9332n5uu9mfq2gqamre6fazx0qa5f4xxmd2e5wx3tq7q2d7nt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueGpsaHNvd0lUV3FqL2Za
            ajhRL1JWcW1kWE13Ri9RbHlVeERWbDNkSkMwCkVSMGJXTGJBZDJTeEZyU1NDdlkr
            eXF5Q0sxdFA2aFRyRE5IL3BibEdWeUUKLS0tIHgzeHU5WXRaSDZjUGFUc3ZaZkJX
            b2IySGJvU2tWRGhzb3FMenBtNHpwUFkK03/jHkJcxjQ4T+NOM5ZsEgZeXk+TZTl0
            I4qSlbmRCjJQwQVCIfLU/a/HP0Kv3wte1o+zb2JSY3vXes/9Eg1DRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-04T10:14:40Z"
    mac: ENC[AES256_GCM,data:BMOHKps4/XDbjp2SWVupF+KM/CmfpDZQvGks8sKnoGMQavDE18qtlLTwbuOtdj2PE8Fh1YQ9y9ZDGQRzjvmBD4Q0szBF2SJ6MpKPwmrHmrDMRn2EtjHFRJU2DiKowd45nGL75dGmux7nGdIGXYhVWHQcVXuFIdYKPYK/NqDlhJE=,iv:yJ1yEKCmzjM/kOq1kTHXTVk7VKNG2wom/+BI+G4a6XE=,tag:es16kJxfaL01TL5qfK6IPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
